# Generated by Django 4.1.5 on 2023-01-16 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_posts_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posts.posts"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postlike",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
