# Generated by Django 4.1.5 on 2023-01-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_postcomment_post_postlike_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_set",
                to="posts.posts",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes_set",
                to="posts.posts",
            ),
        ),
    ]
