version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      POSTGRES_DB: reunion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"