# Generated by Django 4.1.5 on 2023-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followings",
            constraint=models.UniqueConstraint(
                fields=("user", "following"), name="follower_following_unique"
            ),
        ),
    ]
