name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{SECRET_KEY}}
        DEBUG: ${{DEBUG}}
        POSTGRES_DB: ${{POSTGRES_DB}}
        POSTGRES_USER: ${{POSTGRES_USER}}
        POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
        DB_HOST: ${{DB_HOST}}
        DB_PORT: ${{DB_PORT}}
      run: |
        python manage.py test
